version: "3.7"

services:
  human-log-ui:
    build:
      context: "./services/human-log-ui"
    command: flask run --host 0.0.0.0 --port 7070
    env_file:
      - ./deploy/base.env
      - ./deploy/secrets.env
      - ./deploy/local.env
    volumes:
      - "./services/human-log-ui/app:/app"
    ports:
      - "80:7070"
