version: "3.7"

services:
  human-log-ui:
    build:
      context: "./services/human-log-ui"
    env_file:
      - ./deploy/base.env
      - ./deploy/secrets.env
      - ./deploy/local.env
    volumes:
      - "./services/human-log-ui/app/app:/app/app"
    ports:
      - "80:7000"