version: "3.7"

services:
  human-log-ui:
    build:
      context: "./services/human-log-ui"
    env_file:
      - ./deploy/base.env
      - ./deploy/secrets.env
      - ./deploy/prod.env
    image: gcr.io/resilient-tech/humanlog